insert into g_benefit_eval_tpl_item values( 1 , 1 ,"促销项目业务价值评估","收入提升率","desc","refVal",1 );
insert into g_benefit_eval_tpl_item values( 2 , 1 ,"促销项目业务价值评估","实际回报率","desc","refVal",2 );
insert into g_benefit_eval_tpl_item values( 3 , 1 ,"促销项目业务价值评估","新增客户签约率","desc","refVal",3 );
insert into g_benefit_eval_tpl_item values( 4 , 1 ,"促销项目业务价值评估","存量客户保有率提升","desc","refVal",4 );
insert into g_benefit_eval_tpl_item values( 5 , 1 ,"促销项目业务价值评估","其他业务价值","desc","refVal",5 );
insert into g_benefit_eval_tpl_item values( 6 , 2 ,"新建平台项目财务价值评估","净现值","desc","refVal",6 );
insert into g_benefit_eval_tpl_item values( 7 , 2 ,"新建平台项目财务价值评估","内含报酬率","desc","refVal",7 );
insert into g_benefit_eval_tpl_item values( 8 , 2 ,"新建平台项目财务价值评估","动态投资回收期","desc","refVal",8 );
insert into g_benefit_eval_tpl_item values( 9 , 2 ,"新建平台项目业务价值评估","客户新增和保有","desc","refVal",9 );
insert into g_benefit_eval_tpl_item values( 10, 2 ,"新建平台项目业务价值评估","品牌价值提升","desc","refVal",10);
insert into g_benefit_eval_tpl_item values( 11, 2 ,"新建平台项目业务价值评估","竞争因素","desc","refVal",11);
insert into g_benefit_eval_tpl_item values( 12, 2 ,"新建平台项目业务价值评估","平台可拓展性及重复利用率","desc","refVal",12);
insert into g_benefit_eval_tpl_item values( 13, 2 ,"新建平台项目业务价值评估","管理/运营效率提升率","desc","refVal",13);
insert into g_benefit_eval_tpl_item values( 14, 2 ,"新建平台项目业务价值评估","其他业务价值","desc","refVal",14);
insert into g_benefit_eval_tpl_item values( 15, 3 ,"增收型续建平台项目财务价值评估","净现值","desc","refVal",15);
insert into g_benefit_eval_tpl_item values( 16, 3 ,"增收型续建平台项目财务价值评估","内含报酬率","desc","refVal",16);
insert into g_benefit_eval_tpl_item values( 17, 3 ,"增收型续建平台项目财务价值评估","动态投资回收期","desc","refVal",17);
insert into g_benefit_eval_tpl_item values( 18, 3 ,"增收型续建平台项目业务价值评估","客户新增和保有","desc","refVal",18);
insert into g_benefit_eval_tpl_item values( 19, 3 ,"增收型续建平台项目业务价值评估","品牌价值提升","desc","refVal",19);
insert into g_benefit_eval_tpl_item values( 20, 3 ,"增收型续建平台项目业务价值评估","竞争因素","desc","refVal",20);
insert into g_benefit_eval_tpl_item values( 21, 3 ,"增收型续建平台项目业务价值评估","平台可拓展性及重复利用率","desc","refVal",21);
insert into g_benefit_eval_tpl_item values( 22, 3 ,"增收型续建平台项目业务价值评估","管理/运营效率提升率","desc","refVal",22);
insert into g_benefit_eval_tpl_item values( 23, 3 ,"增收型续建平台项目业务价值评估","其他业务价值","desc","refVal",23);
insert into g_benefit_eval_tpl_item values( 24, 4 ,"项目财务价值评估","原项目年平均成本","desc","refVal",24);
insert into g_benefit_eval_tpl_item values( 25, 4 ,"项目财务价值评估","新项目年平均成本","desc","refVal",25);
insert into g_benefit_eval_tpl_item values( 26, 4 ,"非增收型建设平台项目业务价值评估","客户新增和保有","desc","refVal",26);
insert into g_benefit_eval_tpl_item values( 27, 4 ,"非增收型建设平台项目业务价值评估","品牌价值提升","desc","refVal",27);
insert into g_benefit_eval_tpl_item values( 28, 4 ,"非增收型建设平台项目业务价值评估","竞争因素","desc","refVal",28);
insert into g_benefit_eval_tpl_item values( 29, 4 ,"非增收型建设平台项目业务价值评估","平台可拓展性及重复利用率","desc","refVal",29);
insert into g_benefit_eval_tpl_item values( 30, 4 ,"非增收型建设平台项目业务价值评估","管理/运营效率提升率","desc","refVal",30);
insert into g_benefit_eval_tpl_item values( 31, 4 ,"非增收型建设平台项目业务价值评估","其他业务价值","desc","refVal",31);
insert into g_benefit_eval_tpl_item values( 32, 5 ,"新建ICT项目财务价值评估","净现值","desc","refVal",32);
insert into g_benefit_eval_tpl_item values( 33, 5 ,"新建ICT项目财务价值评估","内含报酬率","desc","refVal",33);
insert into g_benefit_eval_tpl_item values( 34, 5 ,"新建ICT项目财务价值评估","动态投资回收期","desc","refVal",34);
insert into g_benefit_eval_tpl_item values( 35, 5 ,"新建ICT项目业务价值评估","客户规模","desc","refVal",35);
insert into g_benefit_eval_tpl_item values( 36, 5 ,"新建ICT项目业务价值评估","标杆效应","desc","refVal",36);
insert into g_benefit_eval_tpl_item values( 37, 5 ,"新建ICT项目业务价值评估","政府重点建设项目","desc","refVal",37);
insert into g_benefit_eval_tpl_item values( 38, 5 ,"新建ICT项目业务价值评估","项目可扩展性","desc","refVal",38);
insert into g_benefit_eval_tpl_item values( 39, 5 ,"新建ICT项目业务价值评估","对市场占有率的影响","desc","refVal",39);
insert into g_benefit_eval_tpl_item values( 40, 5 ,"新建ICT项目业务价值评估","其他业务价值","desc","refVal",40);
insert into g_benefit_eval_tpl_item values( 41, 6 ,"续建ICT项目财务价值评估","净现值","desc","refVal",41);
insert into g_benefit_eval_tpl_item values( 42, 6 ,"续建ICT项目财务价值评估","内含报酬率","desc","refVal",42);
insert into g_benefit_eval_tpl_item values( 43, 6 ,"续建ICT项目财务价值评估","动态投资回收期","desc","refVal",43);
insert into g_benefit_eval_tpl_item values( 44, 6 ,"续建ICT项目业务价值评估","客户规模","desc","refVal",44);
insert into g_benefit_eval_tpl_item values( 45, 6 ,"续建ICT项目业务价值评估","标杆效应","desc","refVal",45);
insert into g_benefit_eval_tpl_item values( 46, 6 ,"续建ICT项目业务价值评估","政府重点建设项目","desc","refVal",46);
insert into g_benefit_eval_tpl_item values( 47, 6 ,"续建ICT项目业务价值评估","项目可扩展性","desc","refVal",47);
insert into g_benefit_eval_tpl_item values( 48, 6 ,"续建ICT项目业务价值评估","对市场占有率的影响","desc","refVal",48);
insert into g_benefit_eval_tpl_item values( 49, 6 ,"续建ICT项目业务价值评估","其他业务价值","desc","refVal",49);
insert into g_benefit_eval_tpl_item values( 50, 7 ,"新产品开发财务价值评估","净现值","desc","refVal",50);
insert into g_benefit_eval_tpl_item values( 51, 7 ,"新产品开发财务价值评估","内含报酬率","desc","refVal",51);
insert into g_benefit_eval_tpl_item values( 52, 7 ,"新产品开发财务价值评估","动态投资回收期","desc","refVal",52);
insert into g_benefit_eval_tpl_item values( 53, 7 ,"新产品开发业务价值评估","战略匹配度","desc","refVal",53);
insert into g_benefit_eval_tpl_item values( 54, 7 ,"新产品开发业务价值评估","商业模式清晰度","desc","refVal",54);
insert into g_benefit_eval_tpl_item values( 55, 7 ,"新产品开发业务价值评估","业界成功案例（成熟度）","desc","refVal",55);
insert into g_benefit_eval_tpl_item values( 56, 7 ,"新产品开发业务价值评估","收入潜力","desc","refVal",56);
insert into g_benefit_eval_tpl_item values( 57, 7 ,"新产品开发业务价值评估","研发可行性","desc","refVal",57);
insert into g_benefit_eval_tpl_item values( 58, 7 ,"新产品开发业务价值评估","风险分析","desc","refVal",58);
insert into g_benefit_eval_tpl_item values( 59, 7 ,"新产品开发业务价值评估","预计研发周期","desc","refVal",59);
insert into g_benefit_eval_tpl_item values( 60, 7 ,"新产品开发业务价值评估","其他","desc","refVal",60);
insert into g_benefit_eval_tpl_item values( 61, 8 ,"新产品开发财务价值评估","累计净利润（1-3年）","desc","refVal",61);
insert into g_benefit_eval_tpl_item values( 62, 8 ,"新产品开发财务价值评估","投资利润率（ARR）","desc","refVal",62);
insert into g_benefit_eval_tpl_item values( 63, 8 ,"新产品开发财务价值评估","静态投资回收期","desc","refVal",63);
insert into g_benefit_eval_tpl_item values( 64, 8 ,"新产品开发业务价值评估","战略匹配度","desc","refVal",64);
insert into g_benefit_eval_tpl_item values( 65, 8 ,"新产品开发业务价值评估","商业模式清晰度","desc","refVal",65);
insert into g_benefit_eval_tpl_item values( 66, 8 ,"新产品开发业务价值评估","竞争优势（成熟度）","desc","refVal",66);
insert into g_benefit_eval_tpl_item values( 67, 8 ,"新产品开发业务价值评估","收入潜力","desc","refVal",67);
insert into g_benefit_eval_tpl_item values( 68, 8 ,"新产品开发业务价值评估","研发可行性","desc","refVal",68);
insert into g_benefit_eval_tpl_item values( 69, 8 ,"新产品开发业务价值评估","研发周期","desc","refVal",69);
insert into g_benefit_eval_tpl_item values( 70, 8 ,"新产品开发业务价值评估","风险分析","desc","refVal",70);
insert into g_benefit_eval_tpl_item values( 71, 8 ,"新产品开发业务价值评估","其他","desc","refVal",71);
